<a href="https://colab.research.google.com/github/dilaraesmer/miuul_python_notes/blob/main/miuul_python_notes_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0,len(a)):
   ab.append(a[i] * b[i])
   print(ab)

[2]
[2, 6]
[2, 6, 12]
[2, 6, 12, 20]


In [2]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a * b 

array([ 2,  6, 12, 20])

In [3]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [4]:
type(np.array([1,2,3,4,5,6]))

numpy.ndarray

In [5]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.random.randint(0,10,size=8)

array([1, 7, 7, 6, 5, 1, 4, 4])

In [7]:
np.random.normal(10,4, (3,4))

array([[12.43894448, 13.79207248, 11.72104514,  7.81411596],
       [ 6.61875089, 17.66745165, 13.3736974 ,  5.7502472 ],
       [ 5.98389704,  4.77258795, 13.67324871,  6.05873993]])

In [8]:
a = np.random.randint(10, size=10)
a

array([9, 0, 8, 4, 9, 3, 0, 7, 7, 2])

In [9]:
a.ndim # n-dimension

1

In [10]:
a.shape

(10,)

In [11]:
a.size

10

In [12]:
a.dtype

dtype('int64')

In [13]:
np.random.randint(1,20, size= 10)

array([18, 12,  2,  8,  6,  2, 16, 18, 19,  8])

In [14]:
np.random.randint(1,20, size= 10).reshape(2,5)

array([[ 1, 17,  7, 13,  4],
       [ 3, 10, 19, 11,  5]])

In [15]:
ar = np.random.randint(1,20, size= 10)
ar.reshape(2,5)

array([[ 1,  8, 15, 18,  8],
       [ 8,  8, 10,  4, 18]])

In [16]:
a = np.random.randint(10, size=10)
a

array([3, 0, 0, 5, 4, 8, 3, 9, 2, 3])

In [17]:
a[0]

3

In [18]:
a[0:4]

array([3, 0, 0, 5])

In [19]:
a[1] = 100

In [20]:
a

array([  3, 100,   0,   5,   4,   8,   3,   9,   2,   3])

In [21]:
d = np.random.randint(10, size=(3,5))
d

array([[5, 5, 6, 3, 5],
       [1, 1, 1, 8, 4],
       [6, 3, 3, 0, 0]])

In [22]:
d[1,1]

1

In [23]:
d[2,4]

0

In [24]:
d[2,4] = 999

In [25]:
d

array([[  5,   5,   6,   3,   5],
       [  1,   1,   1,   8,   4],
       [  6,   3,   3,   0, 999]])

In [26]:
d[1,3] = 5.7

In [27]:
d

array([[  5,   5,   6,   3,   5],
       [  1,   1,   1,   5,   4],
       [  6,   3,   3,   0, 999]])

In [28]:
d[:,0]

array([5, 1, 6])

In [29]:
d[1,:]

array([1, 1, 1, 5, 4])

In [30]:
d[0:2, 0:3]

array([[5, 5, 6],
       [1, 1, 1]])

In [31]:
v = np.arange(0,30,2)
v

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [32]:
v[1]

2

In [33]:
catch = [1,2,3,4]
v[catch]

array([2, 4, 6, 8])

In [34]:
s = np.array([1,2,3,4,5,6,7,8,9])

In [35]:
ab = []
for i in s:
  if i < 4:
    ab.append(i)
ab

[1, 2, 3]

In [36]:
s[s<4]

array([1, 2, 3])

In [37]:
z = np.array([1,2,3,4,4,5,6,8])
z/5

array([0.2, 0.4, 0.6, 0.8, 0.8, 1. , 1.2, 1.6])

In [38]:
z * 5 / 10

array([0.5, 1. , 1.5, 2. , 2. , 2.5, 3. , 4. ])

In [39]:
z ** 2

array([ 1,  4,  9, 16, 16, 25, 36, 64])

In [40]:
z - 2

array([-1,  0,  1,  2,  2,  3,  4,  6])

In [41]:
np.subtract(z, 1)

array([0, 1, 2, 3, 3, 4, 5, 7])

In [42]:
np.add(z, 5)

array([ 6,  7,  8,  9,  9, 10, 11, 13])

In [43]:
np.mean(z)

4.125

In [44]:
np.sum(z)

33

In [45]:
np.min(z)

1

In [46]:
np.max(z)

8

In [47]:
np.var(z)

4.359375

In [48]:
# 7*x0 + x1 = 20
# x0*2 - 4*x1 = 30

In [49]:
a = np.array([[7,2], [1,-4]])
b = np.array([20,30])

In [50]:
np.linalg.solve(a,b)

array([ 4.66666667, -6.33333333])

In [51]:
a = [1,2,3,4,5]
b = [10,11,12,13,14]
a + b

[1, 2, 3, 4, 5, 10, 11, 12, 13, 14]

In [52]:
result = []
for first, second in zip(a,b):
  result.append(first + second)
result 

[11, 13, 15, 17, 19]

In [53]:
import numpy as np
a = np.array([1,2,3,4])

In [ ]:
type(a)

numpy.ndarray

In [54]:
a.dtype

dtype('int64')

In [55]:
f = np.array([1.2, 2.3, 4.5, 5.6])
f.dtype

dtype('float64')

In [56]:
a

array([1, 2, 3, 4])

In [57]:
a[0]

1

In [58]:
a[0] = 12

In [59]:
a

array([12,  2,  3,  4])

In [60]:
a.ndim

1

In [61]:
a.shape

(4,)

In [62]:
a.size

4

In [63]:
f

array([1.2, 2.3, 4.5, 5.6])

In [64]:
a + f

array([13.2,  4.3,  7.5,  9.6])

In [65]:
a * f 

array([14.4,  4.6, 13.5, 22.4])

In [66]:
a / f

array([10.        ,  0.86956522,  0.66666667,  0.71428571])

In [67]:
f ** a

array([  8.91610045,   5.29      ,  91.125     , 983.4496    ])

In [68]:
a

array([12,  2,  3,  4])

In [69]:
a * 10

array([120,  20,  30,  40])

Universal Functions (unfuncs)

In [70]:
np.sin(a)

array([-0.53657292,  0.90929743,  0.14112001, -0.7568025 ])

Slicing Arrays

In [71]:
#         -5 -4 -3 -2 -1
# indices: 0  1  2  3  4 

In [72]:
a = np.array([10,11,12,13,14])
a[1:3]

array([11, 12])

In [73]:
# negative indices work also
a[1:-2]

array([11, 12])

In [74]:
a[-4:3]

array([11, 12])

Omitting Indices

Omitted boundaries are assumed to be the beginning (or end) of the list

In [75]:
# grab first three elements
a[:3]

array([10, 11, 12])

In [76]:
# grab last two elements 
a[-2:]

array([13, 14])

In [77]:
# every other element
a[::2]

array([10, 12, 14])

In [78]:
a = np.arange(25).reshape(5,5)

In [79]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [80]:
a[: , ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [81]:
a[:, 1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [82]:
a[4,:]

array([20, 21, 22, 23, 24])

In [83]:
a[4]

array([20, 21, 22, 23, 24])

In [85]:
a[-1:]

array([[20, 21, 22, 23, 24]])

In [86]:
a[1::2, :4:2]

array([[ 5,  7],
       [15, 17]])

In [87]:
a = np.array([1,2,3,4])

In [89]:
b = a[:2]
b

array([1, 2])

In [92]:
b[0] = -1
b

array([-1,  2])

In [93]:
a

array([-1,  2,  3,  4])